# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box_check_update = false
    
    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 1
        #libvirt.cpuset = '1-4,^3,6'
        #libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
    end    

    config.vm.define "node" do |n|
        #n.vm.box = "hbasria/ubuntu-20.04-server"
        n.vm.box = "builds/package.box"
    end  
  
  end



  


  